[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/.netlify/functions/payment-status/:reference"
  to = "/.netlify/functions/payment-status?reference=:reference"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
